# Import statements

In [2]:
%load_ext autoreload
%autoreload 2

import microfading as mf

import msdb
import pandas as pd
import inspect
import importlib

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Config file

In [ ]:
module = importlib.import_module('microfading')

In [8]:
msdb.update_db_info()

VBox(children=(Combobox(value='', description='DB name', layout=Layout(height='30px', width='20%'), options=('…

HBox(children=(Button(description='Save', style=ButtonStyle(), tooltip='Click me'), Output()))

In [9]:
msdb.get_config_file()

{'databases': {'db_local': {'path_folder': '/home/gpatin/Documents/RCE/databases/'},
  'db_lon': {'path_folder': '/media/lon/development/databases/'},
  'MFT': {'path_folder': '/home/gpatin/Documents/RCE/databases/'},
  'RS': {'path_folder': '/home/gpatin/Documents/RCE/databases/'},
  'testdb': {'path_folder': '/home/patin/Documents/hello'}}}

In [16]:
mf.get_light_dose_info()

         value
unit  He_MJ/m2

In [11]:
mf.get_config()

{'colorimetry': {'observer': '10deg',
  'illuminant': 'D65',
  'white_standard': 'WR4'},
 'databases': {'db_name': 'MFT',
  'path_folder': '/home/gpatin/Documents/RCE/databases/',
  'usage': True},
 'devices': {'MFT1': {'wl_range': [400, 750],
   'process_function': 'MFT_fotonowy'},
  'MFT2': {'wl_range': [400, 750], 'process_function': 'MFT_fotonowy'}},
 'exposure': {'illuminance_lux': 100,
  'hours_per_day': 10,
  'days_per_year': 365},
 'filters': {},
 'functions': {'linear_1p': {'expression': 'c0*x',
   'bounds': '[(-np.inf),(np.inf)]'},
  'linear_2p': {'expression': 'c0*x+c1',
   'bounds': '[(-np.inf,-np.inf),(np.inf,np.inf)]'},
  'power_2p': {'expression': 'c0*(x**c1)',
   'bounds': '[(-np.inf,0),(np.inf,1)]'},
  'power_3p': {'expression': 'c0*(x**c1)+c2',
   'bounds': '[(-np.inf,0,-np.inf),(np.inf,1,np.inf)]'},
  'sigmoid_2p': {'expression': '(c0/(1+np.exp(c1*x)))',
   'bounds': '[(-np.inf,-np.inf),(np.inf,np.inf)]'},
  'sigmoid_3p': {'expression': '(c0/(1+np.exp(c1*x)))+c2',
   'bounds': '[(-np.inf,-np.inf,-np.inf),(np.inf,np.inf,np.inf)]'}},
 'light_dose': {'unit': 'He_MJ/m2'},
 'lamps': {},
 'institution': {'name': 'Rijksdienst voor het Cultureel Erfgoed',
  'acronym': 'RCE',
  'department': 'Rijkserfgoed Laboratorium',
  'address': 'Atelier Gebouw (Amsterdam)'},
 'report_figures': {}}

In [23]:
mf.get_config()['devices']['MFT1']

{'wl_range': [400, 750], 'process_function': 'MFT_fotonowy'}

In [7]:
mf.get_exposure_conditions()

                 value
illuminance_lux    100
hours_per_day       10
days_per_year      365
hours_per_year    3650
yearly_Hv_klxh     365

In [ ]:
db = msdb.DB('MFT')

In [39]:
mf.get_config()

{'colorimetry': {'observer': '10deg',
  'illuminant': 'D65',
  'white_standard': 'WR4'},
 'databases': {'db_name': 'MFT',
  'path_folder': '/home/gpatin/Documents/RCE/databases/',
  'usage': True},
 'devices': {'MFT1': {'wl_range': [400, 750],
   'process_function': 'MFT_fotonowy'},
  'MFT2': {'wl_range': [400, 750], 'process_function': 'MFT_fotonowy'}},
 'exposure': {'illuminance_lux': 100,
  'hours_per_day': 10,
  'days_per_year': 365},
 'filters': {},
 'functions': {'linear_1p': {'expression': 'c0*x',
   'bounds': '[(-np.inf),(np.inf)]'},
  'linear_2p': {'expression': 'c0*x+c1',
   'bounds': '[(-np.inf,-np.inf),(np.inf,np.inf)]'},
  'power_2p': {'expression': 'c0*(x**c1)',
   'bounds': '[(-np.inf,0),(np.inf,1)]'},
  'power_3p': {'expression': 'c0*(x**c1)+c2',
   'bounds': '[(-np.inf,0,-np.inf),(np.inf,1,np.inf)]'},
  'sigmoid_2p': {'expression': '(c0/(1+np.exp(c1*x)))',
   'bounds': '[(-np.inf,-np.inf),(np.inf,np.inf)]'},
  'sigmoid_3p': {'expression': '(c0/(1+np.exp(c1*x)))+c2',
   'bounds': '[(-np.inf,-np.inf,-np.inf),(np.inf,np.inf,np.inf)]'}},
 'light_dose': {'unit': 'He_MJ/m2'},
 'lamps': {},
 'institution': {'name': 'Rijksdienst voor het Cultureel Erfgoed',
  'acronym': 'RCE',
  'department': 'Rijkserfgoed Laboratorium',
  'address': 'Atelier Gebouw (Amsterdam)'},
 'report_figures': {}}

In [38]:
mf.set_devices_info()

VBox(children=(Combobox(value='', description='Device ID', ensure_option=True, layout=Layout(height='30px', wi…

HBox(children=(Button(description='Record info', style=ButtonStyle(), tooltip='Click me'), Output()))

In [ ]:
mf.get_DB()

In [ ]:
mf.config

# Process rawdata

In [35]:
rawfiles = mf.get_datasets(rawfiles=True)
rawfiles

[PosixPath('/home/gpatin/anaconda3/lib/python3.11/site-packages/microfading/datasets/2024-8200 P-001 G01 uncleaned_01-spect_convert.txt'),
 PosixPath('/home/gpatin/anaconda3/lib/python3.11/site-packages/microfading/datasets/2024-8200 P-001 G01 uncleaned_01-spect.txt'),
 PosixPath('/home/gpatin/anaconda3/lib/python3.11/site-packages/microfading/datasets/2024-8200 P-001 G01 uncleaned_01.txt'),
 PosixPath('/home/gpatin/anaconda3/lib/python3.11/site-packages/microfading/datasets/2024-8200 P-001 G01 uncleaned_01.rfc'),
 PosixPath('/home/gpatin/anaconda3/lib/python3.11/site-packages/microfading/datasets/2024-144 BWS0024 G01 BW1_01-spect_convert.txt'),
 PosixPath('/home/gpatin/anaconda3/lib/python3.11/site-packages/microfading/datasets/2024-144 BWS0024 G01 BW1_01-spect.txt'),
 PosixPath('/home/gpatin/anaconda3/lib/python3.11/site-packages/microfading/datasets/2024-144 BWS0024 G01 BW1_01.txt'),
 PosixPath('/home/gpatin/anaconda3/lib/python3.11/site-packages/microfading/datasets/2024-144 BWS0024 G01 BW1_01.rfc')]

In [45]:
mf.process_rawdata(files=rawfiles,device='Fotonowy')

foto

# MFT class